[package]
name = "catware-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "x11",
]}
egui_plot = "0.29.0"
evalexpr = "12.0.1"
pest = "2.7.15"
pest_derive = "2.7.15"
